<a href="https://colab.research.google.com/github/SinghAbh1shek/Numpy/blob/main/Numpy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Method in NumPy

In [ ]:
import numpy as np

# Transpose

> It's covert rows to columns and columns into rows



In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])


In [ ]:
print(array_2d.transpose())
print(array_2d.T)  #We can also write like this

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Sorting

In [ ]:
arr = np.array([1, 3, 2, 54, 6, 8, 7, 2, 5])

In [ ]:
sorted_array = np.sort(arr)
print(sorted_array)

[ 1  2  2  3  5  6  7  8 54]


In [ ]:
arr_2D = np.array([[4, 2, 1], [7, 2, 5]])
sorted_arr_2D = np.sort(arr_2D)
print(sorted_arr_2D)

[[1 2 4]
 [2 5 7]]


In [ ]:
arr_2D = np.array([[4, 3, 2], [7, 1, 5], [3, 2, 1]])
sorted_arr_2D = np.sort(arr_2D, axis=0)   # When axis is 0 its runs vertically down the column
print(sorted_arr_2D)

[[3 1 1]
 [4 2 2]
 [7 3 5]]


In [ ]:
arr_2D = np.array([[4, 3, 2], [7, 1, 5], [3, 2, 1]])
sorted_arr_2D = np.sort(arr_2D, axis=1)   # When axis is 1 its runs horizontally across the rows
print(sorted_arr_2D)

[[2 3 4]
 [1 5 7]
 [1 2 3]]


# argsort()

> Its returns the indexes that would sort an array


In [ ]:
arr = np.array([1, 3, 2, 54, 6, 8, 7, 2, 5])

In [ ]:
print(np.argsort(arr))

[0 2 7 1 8 4 6 5 3]


*Ranking Recommendation Systems*

In [ ]:
similarity_scores = np.array([0.88, 0.21, 0.93, 0.64, 0.52])
sorted_indices = np.argsort(similarity_scores)
print(sorted_indices)
# for top 3
top_3_indices = sorted_indices[-3:][::-1]
print(top_3_indices)

[1 4 3 0 2]
[2 0 3]


# Concatenation Arrays

In [ ]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([3, 4, 5, 6])

arr_3 = np.concatenate((arr_1, arr_2))
print(arr_3)

[1 2 3 3 4 5 6]


In [ ]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])

arr_3 = np.concatenate((arr_1, arr_2), axis=0)
print(arr_3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr_1 = np.array([[1, 2, 3], [4, 5, 6]])
arr_2 = np.array([[7, 8, 9], [10, 11, 12]])

arr_3 = np.concatenate((arr_1, arr_2), axis=1)
print(arr_3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Reshape

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array_2d = arr.reshape(4, 2)
print(array_2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# flatten the Multidimentional array to 1D
arr_1D = array_2d.reshape(-1)
print(arr_1D)

[1 2 3 4 5 6 7 8]


# Split()

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
split_arr = np.split(arr, 4)

In [ ]:
print(split_arr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


# Statistical Operations


> Mean, Median, Mode, Standard Deviations, Min, Max, Sum


In [ ]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
mean_all = np.mean(arr_2d)
print(mean_all)

3.5


In [ ]:
mean_axis_0 = np.mean(arr_2d, axis=0)
print(mean_axis_0)

[2.5 3.5 4.5]


In [ ]:
mean_axis_1 = np.mean(arr_2d, axis=1)
print(mean_axis_1)

array([2., 5.])

In [ ]:
median_all = np.median(arr_2d)
print(median_all)

3.5


In [ ]:
standard_deviation_all = np.std(arr_2d)
print(standard_deviation_all)

1.707825127659933


In [ ]:
min_all = np.min(arr_2d)
print(min_all)

1


In [ ]:
max_all = np.max(arr_2d)
print(max_all)

6


In [ ]:
sum_all = np.sum(arr_2d)
print(sum_all)

21


# Data creations ways of NumPy arrays

In [ ]:
arr1 =np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [ ]:
arr_2d =np.zeros((3, 3))
print(arr_2d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_3d =np.zeros((3, 3, 4), dtype=int)    # dtype=int return int value instead of float
print(arr_3d)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
arr_3d =np.ones((3, 3, 4), dtype=str)    # np.ones returns new array filled with 1
print(arr_3d)

[[['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]

 [['1' '1' '1' '1']
  ['1' '1' '1' '1']
  ['1' '1' '1' '1']]]


In [ ]:
arr_3d =np.full((3, 3, 4), 8, dtype=str)    # np.full returns new array filled with the value we filled
print(arr_3d)

[[['8' '8' '8' '8']
  ['8' '8' '8' '8']
  ['8' '8' '8' '8']]

 [['8' '8' '8' '8']
  ['8' '8' '8' '8']
  ['8' '8' '8' '8']]

 [['8' '8' '8' '8']
  ['8' '8' '8' '8']
  ['8' '8' '8' '8']]]


In [ ]:
identity_3_cross_4 = np.eye(3,4)  # np.eye return a 2-D array with ones on the diagonal and zeros elsewhere.
print(identity_3_cross_4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Arange


> np.arange(start, stop, step_size)





In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

> Random




In [ ]:
np.random.random(5)

array([0.41894772, 0.46730119, 0.32483028, 0.13148147, 0.52573053])

In [ ]:
np.random.random((3, 4))

array([[0.19152996, 0.60218983, 0.16756243, 0.12916586],
       [0.92945389, 0.8911013 , 0.94639053, 0.23666871],
       [0.8218775 , 0.77357423, 0.6358308 , 0.44756932]])

In [ ]:
np.random.seed((25))      # random.seed return the same value at every iteration
np.random.random((3, 4))


array([[0.87012414, 0.58227693, 0.27883894, 0.18591123],
       [0.41110013, 0.11737555, 0.68496874, 0.43761106],
       [0.55622933, 0.36708032, 0.40236573, 0.1130407 ]])

Linspace


> np.linspace(start, stop, num, endpoint, **retstep**, dtype)



In [ ]:
np.linspace(0, 5, 3)  # np.linespace return evenly spaced numbers over a specified interval

array([0. , 2.5, 5. ])