<a href="https://colab.research.google.com/github/SinghAbh1shek/Numpy/blob/main/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy-> Numerical Python: **
It's usually used for scientific computing in Python

In [ ]:
import numpy as np

creation of numpy arrays from list

**1D Array**

In [ ]:
array_from_list = np.array([1, 2, 3, 4, 5])
print(array_from_list)

[1 2 3 4 5]


In [ ]:
type(array_from_list)

numpy.ndarray

In [ ]:
array_from_list.shape
array_from_list.dtype

dtype('int64')



>Itemsize returns the size in bytes of each elements in the arrray



In [ ]:
print("The size of arr_int", array_from_list.itemsize, "bytes")

The size of arr_int 8 bytes




> Data provides a direct buffer to the memory location where the array's data is actually stored



In [ ]:
print("Data buffer", array_from_list.data)

Data buffer <memory at 0x7dc895075f00>


In [ ]:
array_from_tuple = np.array((1, 2, 3, 4, 5))
print(array_from_tuple)

[1 2 3 4 5]


In [ ]:
type(array_from_list)

numpy.ndarray

**2D Array**

In [ ]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
type(array_2d)
array_2d.ndim

2

In [ ]:
array_2d.shape

(3, 3)

**3D Array**

In [ ]:
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6],],
                      [[8, 9, 10],
                       [11, 12, 13]]])
print(array_3d)
type(array_3d)
array_3d.ndim
array_3d.dtype

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]


dtype('int64')

In [ ]:
array_3d.shape

(2, 2, 3)

In [ ]:
array_3d_1 = np.array([[[1, 2, 3],
                      [4, 5, 6],
                      [4, 5, 6]],
                      [[8, 9, 10],
                       [11, 12, 13],
                       [4, 5, 6]]])

array_3d_1.shape


(2, 3, 3)

In [ ]:
array_3d_3 = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                      [[8, 9, 10],
                       [11, 12, 13]],

                       [[8, 9, 10],
                       [11, 12, 13]]
                       ])

array_3d_3.shape


(3, 2, 3)