<a href="https://colab.research.google.com/github/SinghAbh1shek/Numpy/blob/main/Numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Indexing and slicing in numpy

In [ ]:
import numpy as np



#  1D



In [ ]:
array_from_list = np.array([1, 2, 3, 4, 5 ])

In [ ]:
print(array_from_list)

[1 2 3 4 5]




> Indexing



In [ ]:
print(array_from_list[2])

3




> Slicing



In [ ]:
print(array_from_list[1:4])

[2 3 4]


# 2D

In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]




> Indexing



In [ ]:
print(array_2d[2][1])   #array_2d[row index ->][column Index |]

8


In [ ]:
print(array_2d[2, 1])   # We can also write like this

8




> Slicing



In [ ]:
print(array_2d[0:2, 1:])

[[2 3]
 [5 6]]


In [ ]:
print(array_2d[1:, 1:])

[[5 6]
 [8 9]]


# 3D

In [ ]:
array_3d = np.array([[[1, 2, 3], [3, 4, 6], [6, 7, 8]],
                     [[5, 6, 7], [7, 8, 9], [9, 10, 11]],
                     [[9, 10, 11], [12, 13, 14], [14, 15, 16]]])

In [ ]:
print(array_3d)

[[[ 1  2  3]
  [ 3  4  6]
  [ 6  7  8]]

 [[ 5  6  7]
  [ 7  8  9]
  [ 9 10 11]]

 [[ 9 10 11]
  [12 13 14]
  [14 15 16]]]




> Indexing



In [ ]:
print(array_3d[1])  # array_3d[Sub Matrix]

[[ 5  6  7]
 [ 7  8  9]
 [ 9 10 11]]


In [ ]:
print(array_3d[1][1][2])  # array_3d[Sub Matrix][We can use 2d method]
print(array_3d[1][1, 2])  # we can also write like this
print(array_3d[1, 1, 2])  # we can also write like this

9
9
9


In [ ]:
# Question how can access 16?
print(array_3d[2, 2, 2])

[[13 14]]




> Slicing



In [ ]:
# How can we access 4, 6 and 8,9
print(array_3d[0:2, 1, 1:])

[[4 6]
 [8 9]]
