<a href="https://colab.research.google.com/github/SinghAbh1shek/Numpy/blob/main/Numpy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Arithmetic Operation

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

In [ ]:
print(a)
print(b)

print('\naddition:\n', a+b)

print('\nsubtraction:\n', a-b)

print('\ndivision:\n', a/b)

print('\nmultiplication:\n', a*b)

print('\nexponential:\n', a**b)

[[1 2]
 [3 4]]
[[10 20]
 [30 40]]

addition:
 [[11 22]
 [33 44]]

subtraction:
 [[ -9 -18]
 [-27 -36]]

division:
 [[0.1 0.1]
 [0.1 0.1]]

multiplication:
 [[ 10  40]
 [ 90 160]]

exponential:
 [[              1         1048576]
 [205891132094649               0]]
